export const sectionGroups = [
  {
    title: "신선하게 자라난 농산물",
    buttonGroups: [
      { keys: [1], label: "GAP" },
      { keys: [2], label: "우리땅과일" },
      { keys: [3], label: "수입과일" },
      { keys: [4], label: "친환경채소" },
      { keys: [5], label: "우리땅채소" },
      { keys: [6], label: "샐러드채소" },
      { keys: [7, 8], label: "즙용/간편채소" },
      { keys: [9, 10], label: "버섯/건나물" },
      { keys: [11, 12], label: "쌀/잡곡" },
      { keys: [13, 14], label: "견과/선식" },
    ],
  },
  {
    title: "농장에서 식탁까지 신선축산",
    buttonGroups: [
      { keys: [15, 16], label: "유정란/알류" },
      { keys: [17, 19], label: "무항생제한우" },
      { keys: [18, 20], label: "무항생제한돈" },
      { keys: [19], label: "한우" },
      { keys: [20], label: "한돈" },
      { keys: [21], label: "제주돼지" },
      { keys: [22, 23], label: "닭/오리" },
      { keys: [24], label: "소고기" },
      { keys: [25], label: "유기농소고기" },
      { keys: [26, 27], label: "육가공/족발" },
      { keys: [28], label: "양념육" },
    ],
  },
  {
    title: "바다향 가득 품은 수산물",
    buttonGroups: [
      { keys: [29], label: "새벽수산" },
      { keys: [30], label: "일반생선" },
      { keys: [31, 32], label: "연어/참치" },
      { keys: [33, 16], label: "오징어/알류" },
      { keys: [34, 35, 36], label: "새우/조개/멸치" },
      { keys: [37, 38], label: "액젓/젓갈" },
      { keys: [39, 40, 41], label: "김/해조/건어물" },
      { keys: [42, 43], label: "어묵/가공" },
    ],
  },
  {
    title: "요즘 인기있는 간식",
    buttonGroups: [
      { keys: [44, 45], label: "과자/빵" },
      { keys: [46, 47, 48], label: "떡/한과/엿" },
      { keys: [49, 50], label: "두유/유제품" },
      { keys: [51], label: "선식" },
      { keys: [52, 53, 54], label: "사탕/젤리/초콜릿" },
      { keys: [55], label: "시리얼" },
    ],
  },
];
