server:
  port: 8095
  servlet:
    session:
      cookie:
        same-site: lax
        secure: false

spring:
  application:
    name: oasis

  datasource:
#    url: jdbc:mysql://localhost:3306/oasis
    url: jdbc:mysql://oasis-mysql-container:3306/oasis
#    username: root
#    password: 1234
    username: team24
    password: team24pw
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_MAIL_USERNAME}
    password: ${GOOGLE_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      image:
        options:
          model: dall-e-3
          size: 1024x1024
          quality: standard
          response-format: url

upload:
  path: src/main/resources/static/uploads

# 집
#file:
#  upload-dir: G:/oasis/uploads

# 학원
#file:
#  upload-dir: D:/oasis/uploads
#  legacy-dir: D:/oasis/uploads

# AWS
file:
  upload-dir: /uploads
  legacy-dir: /uploads

toss:
  payments:
    test-client-key: ${TOSS_TEST_CLIENT_KEY}
    test-secret-key: ${TOSS_TEST_SECRET_KEY}
    base-url: "https://api.tosspayments.com/v1"
    success-url: "http://3.34.191.154/api/payment/success"
    fail-url: "http://3.34.191.154/api/payment/fail"

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace

