server:
  port: 8094

spring:
  application:
    name: oasis

  datasource:
    url: jdbc:mysql://localhost:3306/oasis
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_MAIL_USERNAME}
    password: ${GOOGLE_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

upload:
  path: src/main/resources/static/upload

file:
  upload-dir: ./src/main/resources/uploads

openai:
  api-key: ${OPENAI_API_KEY}

toss:
  payments:
    test-client-key: ${TOSS_TEST_CLIENT_KEY}
    test-secret-key: ${TOSS_TEST_SECRET_KEY}
    base-url: "https://api.tosspayments.com/v1"
    success-url: "http://localhost:8094/api/payment/success"
    fail-url: "http://localhost:8094/api/payment/fail"


